name: unbox
favicon: null
layout_spectrum: 0.8286892797332257
typography_spectrum: 0.4083898337557912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d8dd'
    - '#0c0c14'
    - '#7ea731'
    - '#825131'
    - '#da9665'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5719800668302923
purpose: []
